swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: User Profile API
      description: Api for view all their transactions for the current month, grouped by account
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Transactions Successfully
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: The JWT token supplied is invalid or corrupted. Please check that the token is correct and has not been tampered with.
        '500':
          description: Internal Server Error
        '401':
          description: Unauthorized
        '404':
          description: Not found
        '422':
          description: Unprocessable entity
  /user/transaction/{transactionId}:
    parameters:
      - name: transactionId
        in: path
        description: Transaction identifier to remove information from the transaction
        required: true
        type: integer
        format: int64
    delete:
      summary: Delete information from a transaction
      description: Allows you to delete specific information from a transaction.
      tags:
        - Transaction Module
      parameters:
        - name: Authorization
          in: header
          description: Attach Bearer JWT token
          required: true
          type: string
      responses:
        '204':
          description: Transaction information successfully deleted
        '404':
          description: The specified transaction was not found
        '500':
          description: Internal Server Error
        '401':
          description: Unauthorized
        '422':
            description: Unprocessable entity
    put:
      tags:
        - Transaction Module
      summary: Modify transaction information
      description: Allows you to modify the information of an existing transaction.
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: body
          description: Update transaction attributes
          required: true
          schema:
            $ref: '#/definitions/UpdateTransactionNote'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction updated successfully
          schema:
            $ref: '#/definitions/UpdateTransactionNote'
        '400':
          description: The JWT token supplied is invalid or corrupted. Please check that the token is correct and has not been tampered with.
        '404':
          description: The specified transaction was not found
        '500':
          description: Internal Server Error
        '401':
          description: Unauthorized
        '422':
          description: Unprocessable entity

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Transaction:
    type: array
    items:
      type: object
      properties:
        transactionId:
          type: integer
        body:
          type: object
          properties:
            idItem:
              type: number
            balance:
              type: number
            date:
              type: string
            description:
              type: string
            amount:
              type: number
            transaction:
              type: string
            category:
              type: string
            notes:
              type: string
  UpdateTransactionNote:
    type: object
    properties:
      transactionId:
        type: integer
      body:
        type: object
        properties:
          idItem:
            type: number
          balance:
            type: number
          date:
            type: string
          description:
            type: string
          amount:
            type: number
          transaction:
            type: string
          category:
            type: string
          notes:
            type: string
  TransactionNote:
    type: object
    properties:
      notes:
        type: string